### ISSUE TITLE
ToDo: List of functions

### ISSUE THREAD

**Issue by jensg-st** [direktiv/apps#1]
### Applications

- [ ] echo
- [ ] ssh
- [ ] ansible
- [ ] imagemagick
- [ ] discord
- [ ] ms teams
- [ ] excel / docs / pdf read
- [ ] excel / docs / pdf write
- [ ] kafka
- [ ] rabbitmq
- [ ] nats
- [ ] pulsar
- [ ] zeromq
- [ ] twilio
- [ ] twitter
- [ ] zip
- [ ] vmware powercli
- [ ] terraform
- [ ] pandoc
- [ ] usql
- [ ] dell srm
- [ ] servicenow
- [ ] google spreadsheet
- [ ] mustache
- [ ] gpg
- [ ] git json
- [ ] ping, nslookup, dns  
- [ ] trivy
- [ ] swagger2markdown
- [ ] kubectl
- [ ] image-magick (+ blur, watermark)
- [ ] yaml2json
- [ ] csv2json
- [ ] karate
- [ ] bash
- [ ] email
